### ISSUE TITLE
Jenkins TF deploy - revisited 

### ISSUE THREAD

**Issue by jonathanlandGit** [bspeagle/Jenkins#2]
I may have spoke too soon. So I tried to his the dns name at 8080 and then added existing infra for subnets and im still getting the same issue where I see that Jenkins is running but im unable to access the app at 8080. Typically, when this runs does it take about 5-10 minutes for everything to load? Also, when debugging were you able to see the logs anywhere in aws. Usually i create a log group but didn't know if you used something else to help you track the progress of the app. Help appreciated.

**Comment by bspeagle** [comment]
Yes. If that wasn't mentioned my apologies. It'll take about 5 - 10 minutes to spin up after infra deployment is done. It's installing python, PHP and docker before it installs Jenkins. After the initial few minutes it should respond with a loading page while Jenkins finishes coming online and then you'll get a prompt for login.

And no, I don't have logs being sent to cloudwatch. Since everything is happening in cloud-init you can view the system logs for the instance to see events related to install.

Give all that a whirl and let me know.

**Comment by jonathanlandGit** [comment]
Np yeah figured out the issue actually. There were a few additions needed with the script w/ the existing infra I am using. Apparently with some recent updates and the actually install of Jenkins was breaking. I got it working but be had to include the epel install before the Jenkins install cmd in the tpl file. It was missing some dependencies. Refactored the TF code as well and again things are working great now. 

Yes was looking in system logs but that is really limited in what you can actually  see so was hoping there was a workaround. I think if I included an arn of some sort on cloudwatch resource that that may work. Will work on that a bit more.

**Comment by bspeagle** [comment]
Can you create a pull request for your change and I’ll get it merged in

**Comment by jonathanlandGit** [comment]
Yes it may be tomorrow when I can but I will, np.

**Comment by jonathanlandGit** [comment]
Pull request created

**Comment by bspeagle** [comment]
merged!
